In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')


In [5]:
train_hr=pd.read_csv(r'C:\Users\vaish\Downloads\train_hr.csv',index_col=0)
test_hr=pd.read_csv('test_hr.csv')
train_hr.head()


department     region         education gender  \
employee_id                                                          
65438        Sales & Marketing   region_7  Master's & above      f   
65141               Operations  region_22        Bachelor's      m   
7513         Sales & Marketing  region_19        Bachelor's      m   
2542         Sales & Marketing  region_23        Bachelor's      m   
48945               Technology  region_26        Bachelor's      m   

            recruitment_channel  no_of_trainings  age  previous_year_rating  \
employee_id                                                                   
65438                  sourcing                1   35                   5.0   
65141                     other                1   30                   5.0   
7513                   sourcing                1   34                   3.0   
2542                      other                2   39                   1.0   
48945                     other                1   45                   3.0   

             length_of_service  KPIs_met >80%  awards_won?  \
employee_id                                                  
65438                        8              1            0   
65141                        4              0            0   
7513                         7              0            0   
2542                        10              0            0   
48945                        2              0            0   

             avg_training_score  is_promoted  
employee_id                                   
65438                        49            0  
65141                        60            0  
7513                         50            0  
2542                         50            0  
48945                        73            0

In [6]:
print(train_hr.shape)
print(test_hr.shape)

(54808, 13)
(23490, 13)


In [7]:
train_hr.isnull().sum()

department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [8]:
test_hr.isnull().sum()

employee_id                0
department                 0
region                     0
education               1034
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    1812
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
dtype: int64

In [9]:
for x in train_hr.columns:
    if train_hr[x].dtype=='object' or train_hr[x].dtype=='bool':
        train_hr[x].fillna(train_hr[x].mode()[0],inplace=True)
    elif train_hr[x].dtype=='int64' or train_hr[x].dtype=='float64':
        train_hr[x].fillna(round(train_hr[x].mean()),inplace=True)

In [10]:
train_hr.isnull().sum()

department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [11]:
for x in test_hr.columns:
    if test_hr[x].dtype=='object' or test_hr[x].dtype=='bool':
        test_hr[x].fillna(test_hr[x].mode()[0],inplace=True)
    elif test_hr[x].dtype=='int64' or test_hr[x].dtype=='float64':
        test_hr[x].fillna(round(test_hr[x].mean()),inplace=True)

In [12]:
test_hr.isnull().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
dtype: int64

In [13]:
colname=[]
for x in train_hr.columns:
    if train_hr[x].dtype=='object':
        colname.append(x)
print(colname)

['department', 'region', 'education', 'gender', 'recruitment_channel']


In [14]:
from sklearn.preprocessing import LabelEncoder
 
le=LabelEncoder() #create object
 
for x in colname:
    train_hr[x]=le.fit_transform(train_hr[x])

In [15]:
train_hr.head()

department  region  education  gender  recruitment_channel  \
employee_id                                                               
65438                 7      31          2       0                    2   
65141                 4      14          0       1                    0   
7513                  7      10          0       1                    2   
2542                  7      15          0       1                    0   
48945                 8      18          0       1                    0   

             no_of_trainings  age  previous_year_rating  length_of_service  \
employee_id                                                                  
65438                      1   35                   5.0                  8   
65141                      1   30                   5.0                  4   
7513                       1   34                   3.0                  7   
2542                       2   39                   1.0                 10   
48945                      1   45                   3.0                  2   

             KPIs_met >80%  awards_won?  avg_training_score  is_promoted  
employee_id                                                               
65438                    1            0                  49            0  
65141                    0            0                  60            0  
7513                     0            0                  50            0  
2542                     0            0                  50            0  
48945                    0            0                  73            0

In [16]:
colname=[]
for x in test_hr.columns:
    if test_hr[x].dtype=='object':
        colname.append(x)
print(colname)

['department', 'region', 'education', 'gender', 'recruitment_channel']


In [17]:
from sklearn.preprocessing import LabelEncoder
 
le=LabelEncoder() #create object
 
for x in colname:
    test_hr[x]=le.fit_transform(test_hr[x])

In [18]:
test_hr.head()

employee_id  department  region  education  gender  recruitment_channel  \
0         8724           8      18          0       1                    2   
1        74430           2      28          0       0                    0   
2        72255           7       4          0       1                    0   
3        38562           5      11          0       0                    0   
4        64486           1      21          0       1                    2   

   no_of_trainings  age  previous_year_rating  length_of_service  \
0                1   24                   3.0                  1   
1                1   31                   3.0                  5   
2                1   31                   1.0                  4   
3                3   31                   2.0                  9   
4                1   30                   4.0                  7   

   KPIs_met >80%  awards_won?  avg_training_score  
0              1            0                  77  
1              0            0                  51  
2              0            0                  47  
3              0            0                  65  
4              0            0                  61

In [19]:
X=train_hr.values[:,0:-1]
Y=train_hr.values[:,-1]
Y=Y.astype(int)

In [20]:
print(X.shape)
print(Y.shape)

(54808, 12)
(54808,)


In [21]:
from sklearn.preprocessing import StandardScaler
# create an object
scaler=StandardScaler()

scaler.fit(X)
X=scaler.transform(X)
#X=scalar.fit_transform(X)


In [22]:
X

array([[ 0.80893285,  1.77652645,  1.61975831, ...,  1.35687789,
        -0.15401776, -1.07593145],
       [-0.38818322, -0.16303375, -0.62883817, ..., -0.73698599,
        -0.15401776, -0.25328242],
       [ 0.80893285, -0.61940086, -0.62883817, ..., -0.73698599,
        -0.15401776, -1.00114517],
       ...,
       [-1.98433798, -1.76031862, -0.62883817, ...,  1.35687789,
        -0.15401776,  1.1676568 ],
       [ 0.80893285,  2.00471   , -0.62883817, ..., -0.73698599,
        -0.15401776, -1.37507655],
       [-1.1862606 , -0.16303375, -0.62883817, ..., -0.73698599,
        -0.15401776, -1.07593145]])

In [23]:
from sklearn.model_selection import train_test_split
 
#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, 
                                                    random_state=10)  

In [24]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(38365, 12)
(16443, 12)
(38365,)
(16443,)


In [25]:
from sklearn.tree import DecisionTreeClassifier

# create model object 
model_DecisionTree=DecisionTreeClassifier(random_state=10,criterion='gini')
# fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)

Y_pred=model_DecisionTree.predict(X_test)


print(list(zip(Y_test,Y_pred)))


[(0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 1), (0, 0), (0, 0), (0, 0), (0, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (1, 0), (0, 0), (0, 1), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (1, 0), (0, 0), (0, 0), (0, 1), (0, 0), (0, 1), (0, 0), (0, 1), (0, 0), (0, 0), (0, 0), (0, 0),

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[14070   994]
 [  758   621]]
Classification report: 
              precision    recall  f1-score   support

           0       0.95      0.93      0.94     15064
           1       0.38      0.45      0.41      1379

    accuracy                           0.89     16443
   macro avg       0.67      0.69      0.68     16443
weighted avg       0.90      0.89      0.90     16443

Accuracy of the model:  0.8934501003466521


In [27]:
model_DecisionTree.feature_importances_

array([0.14422965, 0.10060355, 0.01869252, 0.02688268, 0.03177112,
       0.02821685, 0.13838802, 0.05676809, 0.09194824, 0.04309428,
       0.02419621, 0.29520879])

In [28]:
print((list(zip(train_hr.columns[0:-1],
               model_DecisionTree.feature_importances_))))

[('department', 0.14422965178226851), ('region', 0.10060355097774999), ('education', 0.01869251576651501), ('gender', 0.026882684935266986), ('recruitment_channel', 0.03177111748433791), ('no_of_trainings', 0.02821684781109359), ('age', 0.1383880170318543), ('previous_year_rating', 0.05676808544903955), ('length_of_service', 0.09194824371245482), ('KPIs_met >80%', 0.04309428382734384), ('awards_won?', 0.024196209599423462), ('avg_training_score', 0.29520879162265196)]


In [29]:
sample=pd.DataFrame()
 
sample["Column"]=train_hr.columns[0:-1]
sample["Imp value"]=model_DecisionTree.feature_importances_
 
sample.sort_values("Imp value",ascending=False)

Column  Imp value
11    avg_training_score   0.295209
0             department   0.144230
6                    age   0.138388
1                 region   0.100604
8      length_of_service   0.091948
7   previous_year_rating   0.056768
9          KPIs_met >80%   0.043094
4    recruitment_channel   0.031771
5        no_of_trainings   0.028217
3                 gender   0.026883
10           awards_won?   0.024196
2              education   0.018693

In [30]:
from sklearn.linear_model import LogisticRegression

# create model object 
classifier=LogisticRegression()

# train model object
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)

print(Y_pred)

[0 0 0 ... 0 0 0]


In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[14994    70]
 [ 1273   106]]
Classification report: 
              precision    recall  f1-score   support

           0       0.92      1.00      0.96     15064
           1       0.60      0.08      0.14      1379

    accuracy                           0.92     16443
   macro avg       0.76      0.54      0.55     16443
weighted avg       0.89      0.92      0.89     16443

Accuracy of the model:  0.9183239068296539


In [32]:
y_pred_prob=classifier.predict_proba(X_test)
print(y_pred_prob)


[[0.98745003 0.01254997]
 [0.99263714 0.00736286]
 [0.96705455 0.03294545]
 ...
 [0.98908364 0.01091636]
 [0.91265606 0.08734394]
 [0.9579009  0.0420991 ]]


In [33]:
for a in np.arange(0.4,0.61,0.01):                       #array out of range #(if 0.4 is threshold all values will be compared w 0.4)
    predict_mine = np.where(y_pred_prob[:,1] > a, 1, 0)  #if else logic(traverses through prob matrix(class1 column))
    cfm=confusion_matrix(Y_test, predict_mine)           # just generating confusion matrix
    total_err=cfm[0,1]+cfm[1,0]                          #(printing error whether particular threshold is good or bad)
    print("Errors at threshold ", a, ":",total_err, " , type 2 error :", 
          cfm[1,0]," , type 1 error:", cfm[0,1])

Errors at threshold  0.4 : 1397  , type 2 error : 1205  , type 1 error: 192
Errors at threshold  0.41000000000000003 : 1384  , type 2 error : 1215  , type 1 error: 169
Errors at threshold  0.42000000000000004 : 1371  , type 2 error : 1226  , type 1 error: 145
Errors at threshold  0.43000000000000005 : 1357  , type 2 error : 1232  , type 1 error: 125
Errors at threshold  0.44000000000000006 : 1346  , type 2 error : 1240  , type 1 error: 106
Errors at threshold  0.45000000000000007 : 1342  , type 2 error : 1248  , type 1 error: 94
Errors at threshold  0.4600000000000001 : 1337  , type 2 error : 1254  , type 1 error: 83
Errors at threshold  0.4700000000000001 : 1339  , type 2 error : 1258  , type 1 error: 81
Errors at threshold  0.4800000000000001 : 1336  , type 2 error : 1262  , type 1 error: 74
Errors at threshold  0.4900000000000001 : 1339  , type 2 error : 1267  , type 1 error: 72
Errors at threshold  0.5000000000000001 : 1343  , type 2 error : 1273  , type 1 error: 70
Errors at thres

In [34]:
y_pred_class=[]
for value in y_pred_prob[:,1]:
    if value > 0.46:
        y_pred_class.append(1)
    else:
        y_pred_class.append(0)
print(y_pred_class)



[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,y_pred_class)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,y_pred_class))
 
acc=accuracy_score(Y_test, y_pred_class)
print("Accuracy of the model: ",acc)

[[14981    83]
 [ 1254   125]]
Classification report: 
              precision    recall  f1-score   support

           0       0.92      0.99      0.96     15064
           1       0.60      0.09      0.16      1379

    accuracy                           0.92     16443
   macro avg       0.76      0.54      0.56     16443
weighted avg       0.90      0.92      0.89     16443

Accuracy of the model:  0.918688803746275


Not Promoted: class 0
Promoted: class 1


our class of importance here is class 1(promoted) but logistic regression is not giving good recall value on class 1 because majority of training data is for class 0
 
Data must not have been clearly separable hence logistic regression did not perform good

it is a imbalanced dataset 
we will use techniques like oversampling/up-sampling ,undersampling/down -sampling and SMOTE(Synthetic Minority Oversampling Technique)

In [38]:
X=train_hr.values[:,:-1]
Y=train_hr.values[:,-1]

In [39]:
from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()

scaler.fit(X)

X= scaler.transform(X)

In [40]:
from sklearn.model_selection import train_test_split
  
# split into 70:30 ratio
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, 
                                                    random_state = 10)
  

In [41]:
print("Before OverSampling, counts of label '1': ", (sum(Y_train == 1)))
print("Before OverSampling, counts of label '0': ", (sum(Y_train == 0)))
  
# import SMOTE from imblearn library
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 10,k_neighbors=5)
X_train_res, Y_train_res = sm.fit_resample(X_train, Y_train)# memory graph fit,resample 
  
print('After OverSampling, the shape of train_X: ', (X_train_res.shape))
print('After OverSampling, the shape of train_y: ', (Y_train_res.shape))
  
print("After OverSampling, counts of label '1': ", (sum(Y_train_res == 1)))
print("After OverSampling, counts of label '0': ", (sum(Y_train_res == 0)))

Before OverSampling, counts of label '1':  3289
Before OverSampling, counts of label '0':  35076
After OverSampling, the shape of train_X:  (70152, 12)
After OverSampling, the shape of train_y:  (70152,)
After OverSampling, counts of label '1':  35076
After OverSampling, counts of label '0':  35076


In [42]:
# logistic regression object
lr = LogisticRegression()
  
# train the model on train set
lr.fit(X_train_res, Y_train_res)
  
Y_pred = lr.predict(X_test)

In [43]:
# print classification report
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test, Y_pred))
print(accuracy_score(Y_test, Y_pred))

[[10809  4255]
 [  427   952]]
              precision    recall  f1-score   support

         0.0       0.96      0.72      0.82     15064
         1.0       0.18      0.69      0.29      1379

    accuracy                           0.72     16443
   macro avg       0.57      0.70      0.56     16443
weighted avg       0.90      0.72      0.78     16443

0.7152587727300371
